### ISSUE TITLE
dataset.save(): 'dict' object has no attribute 'save_to_disk'

### ISSUE THREAD

**Issue by markusdr** [stochasticai/xturing#189]
I tried to create and save a dataset, following the documentation (https://xturing.stochastic.ai/datasets/usage#instructiondataset): 

    from xturing.datasets.instruction_dataset import InstructionDataset
    dataset = InstructionDataset({
            "text": ["first text", "second text"],
            "target": ["first text", "second text"],
            "instruction": ["first instruction", "second instruction"]
        })
    dataset.save('foo')

It gives an error:

    ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
    │ /home/ec2-user/tmp/xturing2_data.py:9 in <module>                                                │
    │                                                                                                  │
    │    6 │   │   "instruction": ["first instruction", "second instruction"]                          │
    │    7 │   })                                                                                      │
    │    8                                                                                             │
    │ ❱  9 dataset.save('foo')                                                                         │
    │   10                                                                                             │
    │                                                                                                  │
    │ /home/ec2-user/xturing/src/xturing/datasets/instruction_dataset.py:126 in save                   │
    │                                                                                                  │
    │   123 │   │   return self.data["train"][idx]                                                     │
    │   124 │                                                                                          │
    │   125 │   def save(self, path):                                                                  │
    │ ❱ 126 │   │   return self.data.save_to_disk(path)                                                │
    │   127 │                                                                                          │
    │   128 │   @classmethod                                                                           │
    │   129 │   def generate_dataset(                                                                  │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
    AttributeError: 'dict' object has no attribute 'save_to_disk'

Looks like it's trying to call `save_to_disk` on the internal `data` dict.

**Comment by StochasticRomanAgeev** [comment]
Hi @markusdr,
We released fix for this issue
Please do `pip install xturing -U`

**Comment by markusdr** [comment]
Thanks for the fix! Now the dataset can be saved, but it cannot be loaded afterwards:

    from xturing.datasets.instruction_dataset import InstructionDataset
    dataset = InstructionDataset({
            "text": ["first text", "second text"],
            "target": ["first text", "second text"],
            "instruction": ["first instruction", "second instruction"]
        })
    dataset.save('foo') # Works now!
    d = InstructionDataset('foo') # AssertionError: The dataset should have a train split

I'm sure it's another easy fix. :-)

**Comment by kopyl** [comment]
@StochasticRomanAgeev you did not fix it.
![image](https://github.com/stochasticai/xTuring/assets/17604849/fca39152-cac8-40a2-b2dc-dbf2fc08981f)

**Comment by lukemunn** [comment]
I have the same issue. 

`>>> dataset.save('home/XXX/venv/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/XXX/venv/lib/python3.10/site-packages/xturing/datasets/text_dataset.py", line 56, in save
    return self.data.save_to_disk(path)
AttributeError: 'dict' object has no attribute 'save_to_disk'`

**Comment by kopyl** [comment]
hell, this library seems abandoned. What a shame. Unsubscribing from notifications...
